CREATE DATABASE HEALT;

CREATE TABLE "COURSE"(
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "DESCRIPTION" VARCHAR(1000) NOT NULL,
  "ONE_TRAINING_PRICE" DOUBLE
);