SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `HEALTH` ;
CREATE SCHEMA IF NOT EXISTS `HEALTH` DEFAULT CHARACTER SET ascii ;
USE `HEALTH` ;

-- -----------------------------------------------------
-- Table `HEALTH`.`TRAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`TRAINER` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`TRAINER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `LAST_NAME` VARCHAR(255) NOT NULL ,
  `FIRST_NAME` VARCHAR(255) NOT NULL ,
  `MIDDLE_NAME` VARCHAR(255) NULL ,
  `SEX` VARCHAR(2) NOT NULL ,
  `BIRTH_DATE` DATE NULL ,
  `ABOUTH` TEXT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`TRAINER` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`TIME_SHEET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`TIME_SHEET` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`TIME_SHEET` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`TIME_SHEET` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`COURSE` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`COURSE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` TEXT NULL ,
  `ONE_TRAINING_PRICE` INT(11) NOT NULL ,
  `TYPE` VARCHAR(45) NOT NULL DEFAULT 'GROUP' ,
  `TRAINER_ID` INT NOT NULL ,
  `TIME_SHEET_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_COURSE_TRAINER`
    FOREIGN KEY (`TRAINER_ID` )
    REFERENCES `HEALTH`.`TRAINER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COURSE_TIME_SHEET1`
    FOREIGN KEY (`TIME_SHEET_ID` )
    REFERENCES `HEALTH`.`TIME_SHEET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`COURSE` (`ID` ASC) ;

CREATE INDEX `fk_COURSE_TRAINER` ON `HEALTH`.`COURSE` (`TRAINER_ID` ASC) ;

CREATE INDEX `fk_COURSE_TIME_SHEET1` ON `HEALTH`.`COURSE` (`TIME_SHEET_ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`CLIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`CLIENT` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`CLIENT` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `LAST_NAME` VARCHAR(255) NOT NULL ,
  `FIRST_NAME` VARCHAR(255) NOT NULL ,
  `MIDDLE_NAME` VARCHAR(255) NULL ,
  `SEX` VARCHAR(2) NOT NULL ,
  `BIRTH_DATE` DATE NULL ,
  `ABOUTH` TEXT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`CLIENT` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`CLIENT_HAS_COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`CLIENT_HAS_COURSE` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`CLIENT_HAS_COURSE` (
  `CLIENT_ID` INT NOT NULL ,
  `COURSE_ID` INT NOT NULL ,
  PRIMARY KEY (`CLIENT_ID`, `COURSE_ID`) ,
  CONSTRAINT `fk_CLIENT_has_COURSE_CLIENT1`
    FOREIGN KEY (`CLIENT_ID` )
    REFERENCES `HEALTH`.`CLIENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENT_has_COURSE_COURSE1`
    FOREIGN KEY (`COURSE_ID` )
    REFERENCES `HEALTH`.`COURSE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CLIENT_has_COURSE_COURSE1` ON `HEALTH`.`CLIENT_HAS_COURSE` (`COURSE_ID` ASC) ;

CREATE INDEX `fk_CLIENT_has_COURSE_CLIENT1` ON `HEALTH`.`CLIENT_HAS_COURSE` (`CLIENT_ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`ABONEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`ABONEMENT` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`ABONEMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `COURSE_ID` INT NOT NULL ,
  `TRAINING_COUNT` INT NOT NULL ,
  `PRICE` INT NOT NULL ,
  `DESCRIPTION` TEXT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_ABONEMENT_COURSE1`
    FOREIGN KEY (`COURSE_ID` )
    REFERENCES `HEALTH`.`COURSE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ABONEMENT_COURSE1` ON `HEALTH`.`ABONEMENT` (`COURSE_ID` ASC) ;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`ABONEMENT` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `HEALTH`.`TRAINING_TIME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HEALTH`.`TRAINING_TIME` ;

CREATE  TABLE IF NOT EXISTS `HEALTH`.`TRAINING_TIME` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `DAY` VARCHAR(45) NOT NULL ,
  `START` TIME NOT NULL ,
  `END` TIME NOT NULL ,
  `PLACE` VARCHAR(255) NOT NULL ,
  `TIME_SHEET_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_TRAINING_TIME_TIME_SHEET1`
    FOREIGN KEY (`TIME_SHEET_ID` )
    REFERENCES `HEALTH`.`TIME_SHEET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `HEALTH`.`TRAINING_TIME` (`ID` ASC) ;

CREATE INDEX `fk_TRAINING_TIME_TIME_SHEET1` ON `HEALTH`.`TRAINING_TIME` (`TIME_SHEET_ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
